# Node.js with React
 # Build a Node.js project that uses React.
 # Add steps that analyze code, save build artifacts, deploy, and more:
 # https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 
 
pool:
  vmImage: 'Ubuntu 16.04'
   
steps:
#- task: CopyFiles@2
#  inputs:
#    sourceFolder: '/home/vsts/work/1/s/Solution/orders-ui'
#    contents: '**\*' 
#    cleanTargetFolder: 'true'
#    targetFolder: '/home/vsts/work/1/s/'
    
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
    
- script: |
     npm install
     npm run build
  displayName: 'npm install and build'
